# unite {{{1
# ============================================================================
[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'basyura/unite-mdfind'
on_source = 'unite.vim'
# }}}

[[plugins]]
repo = 'Shougo/vimfiler.vim'
on_source = 'unite.vim'
on_map = '<Plug>'

# vimshell {{{1
# ============================================================================
[[plugins]]
repo = 'Shougo/vimshell.vim'
depends = ['vim-vcs', 'unite.vim']
on_cmd = ['VimShell', 'VimShellBufferDir', 'VimShellInteractive', 'VimShellPop']

[[plugins]]
repo = 'Shougo/vim-vcs'
# }}}

[[plugins]]
repo = 'oplatek/Conque-Shell'
on_cmd = ['ConqueTerm', 'ConqueTermSplit', 'ConqueTermTab', 'ConqueTermVSplit']

# neocomplete {{{1
# ============================================================================
[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = [
    'neoinclude.vim',
    'neosnippet.vim', 'vim-snippets'
]
on_i = 1
# vim_version = '7.3.825'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'
# vim_version = '7.3.825'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'honza/vim-snippets'

# operator {{{1
# ============================================================================
[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
on_map = '<plug>(operator-surround-'

[[plugins]]
repo = 'tyru/operator-camelize.vim'
depends = 'vim-operator-user'
on_map = '<Plug>(operator-camelize-'

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
on_map = '<Plug>(operator-replace)'

[[plugins]]
repo = 'osyo-manga/vim-operator-search'
depends = 'vim-operator-user'
on_map = '<Plug>(operator-search)'

# textobj {{{1
# ============================================================================
[[plugins]]
repo = 'kana/vim-textobj-entire'
on_map = '<Plug>(textobj-entire'

[[plugins]]
repo = 'osyo-manga/vim-textobj-context'
on_map = '<Plug>(textobj-context-'

[[plugins]]
repo = 'kana/vim-textobj-lastpat'
on_map = '<Plug>(textobj-lastpat-'
# }}}

[[plugins]]
repo = 'tmsanrinsha/vim-fakeclip'
if = "$SSH_CLIENT != ''"
on_map = '<Plug>'

[[plugins]]
repo = 'tmsanrinsha/DirDiff.vim'
on_cmd = 'DirDiff'

[[plugins]]
repo = 'osyo-manga/vim-marching'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'maksimr/vim-jsbeautify'
external_commands = 'node'
on_ft = ['javascript', 'css', 'html']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'tmsanrinsha/previm'
on_cmd = ['PrevimOpen']
on_ft = ['markdown']

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_cmd = ['TableModeToggle', 'Tableize', 'TableAddFormula', 'TableEvalFormulaLine']

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'
on_cmd = ['AnsiEsc']

[[plugins]]
repo = 'LeafCage/yankround.vim'
on_map = '<Plug>'
on_sources = 'unite.vim'
# vim_version = '7.3'

[[plugins]]
repo = 'glts/vim-textobj-comment'
on_map = '<Plug>(textobj-comment-'

[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = 'GundoToggle'

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'quark-zju/vim-cpp-auto-include'
external_commands = 'ruby'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
on_map = '<Plug>(easymotion-'

[[plugins]]
repo = 'thinca/vim-ref'
on_cmd = ['Ref', 'Man']

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
depends = ['vim-quickrun', 'shabadou.vim', 'vim-hier', 'quickfixstatus', 'vim-qfsigns']

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'KazuakiM/vim-qfsigns'

[[plugins]]
repo = 'joonty/vdebug'
on_ft = ['php']

[[plugins]]
repo = 'kana/vim-smartword'
on_map = '<Plug>'

[[plugins]]
repo = 'thinca/vim-partedit'
on_cmd = 'Partedit'

[[plugins]]
repo = 't9md/vim-quickhl'
on_map = '<Plug>(quickhl-'

[[plugins]]
repo = 'DrawIt'
on_map = ';di'
on_cmd = 'DrawIt'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'php']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_func = ['openbrowser#search', 'OpenBrowser']
on_map = '<Plug>(openbrowser-'

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_source = 'unite.vim'

[[plugins]]
repo = 'glidenote/memolist.vim'
on_cmd = ['MemoNew', 'MemoList', 'MemoGrep']

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = 'unite.vim'
on_cmd = ['Junkfile', 'JunkfileOpen', 'JunkfileFiletype']

[[plugins]]
repo = 'mattn/qiita-vim'
on_source = 'unite.vim'
on_cmd = ['Qiita']

[[plugins]]
repo = 'mattn/gist-vim'
depends = 'webapi-vim'
on_cmd = ['Gist']

[[plugins]]
repo = 'neilagabriel/vim-geeknote'
on_cmd = ['Geeknote']

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
depends = ['jedi-vim']
on_ft = ['python', 'python3']

[[plugins]]
repo = 'haya14busa/vim-asterisk'
on_map = '<Plug>(asterisk-'

[[plugins]]
repo = 'kannokanno/vim-helpnew'
on_cmd = 'HelpNew'

[[plugins]]
repo = 'rbtnn/vimconsole.vim'
on_cmd = 'VimConsoleToggle'

[[plugins]]
repo = 'tomtom/tcomment_vim'
on_map = ['<Plug>TComment_', 'gc']

[[plugins]]
repo = 'stephpy/vim-php-cs-fixer'
on_ft = ['PhpCsFixerFixDirectory', 'PhpCsFixerFixFile']

[[plugins]]
repo = 'gregsexton/gitv'
on_cmd = ['Gitv']
