[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'tmsanrinsha/unite-ghq'

[[plugins]]
repo = 'thinca/vim-unite-history'

[[plugins]]
repo = 'ujihisa/unite-locate'

[[plugins]]
repo = 'tacroe/unite-mark'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'ujihisa/vimshell-ssh'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'tsukkee/unite-tag'

[[plugins]]
repo = 'rhysd/unite-zsh-cdr.vim'

[[plugins]]
repo = 'Shougo/neossh.vim'

[[plugins]]
repo = 'ujihisa/neco-look'
# external_commands = 'look'
# vim_version = '7.3.825'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'ciaranm/detectindent'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tmsanrinsha/diffchar.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'sudo.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'sgur/vim-textobj-parameter'

[[plugins]]
repo = 'savevers.vim'

[[plugins]]
repo = 'kopischke/vim-fetch'

[[plugins]]
repo = 'QuickFixCurrentNumber'
depends = 'ingo-library'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'osyo-manga/vital-coaster'

[[plugins]]
repo = 'tmsanrinsha/vim-emacscommandline'

[[plugins]]
repo = 'tpope/vim-fugitive'
augroup = 'fugitive'

[[plugins]]
repo = 'ingo-library'

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['shabadou.vim', 'vim-hier', 'quickfixstatus', 'vim-qfsigns', 'vimconsole.vim']

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'kana/vim-gf-user'

[[plugins]]
repo = 'LeafCage/foldCC'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'thinca/vim-template'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'kana/vim-textobj-function'

[[plugins]]
repo = 'kentaro/vim-textobj-function-php'

[[plugins]]
repo = 'kana/vim-textobj-indent'

[[plugins]]
repo = 'rhysd/vim-textobj-conflict'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tmsanrinsha/molokai'
name = 'my_molokai'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'

[[plugins]]
repo = 'thinca/vim-singleton'

[[plugins]]
repo = 'itchyny/lightline.vim'
# depends = ['vim-fugitive', 'tagbar', 'vim-anzu']

[[plugins]]
repo = 'thinca/vim-prettyprint'

[[plugins]]
repo = 'superbrothers/vim-vimperator'

[[plugins]]
repo = 'PreserveNoEOL'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'kana/vim-gf-diff'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

# arduino
[[plugins]]
repo = '4Evergreen4/vim-hardy'

# confluence
[[plugins]]
repo = 'confluencewiki.vim'

# graphviz
[[plugins]]
repo = 'wannesm/wmgraphviz.vim'

# javascript
[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'nono/jquery.vim'

# JSON
[[plugins]]
repo = 'elzr/vim-json'

# markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'

# yaml frontmatterがヘッダーと判定されてしまうのでコメントアウト
# [[plugins]]
# repo = 'nelstrom/vim-markdown-folding'

# MQL4
[[plugins]]
repo = 'vobornik/vim-mql4'

# PHP
[[plugins]]
repo = 'shawncplus/phpcomplete.vim'

[[plugins]]
repo = 'StanAngeloff/php.vim'

# python
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'

# R lang
[[plugins]]
repo = 'jcfaria/Vim-R-plugin'

# shell
[[plugins]]
repo = 'sh.vim--Cla'

# SQL hive
[[plugins]]
repo = 'autowitch/hive.vim'

[[plugins]]
repo = 'cespare/vim-toml'

# tmux
[[plugins]]
repo = 'zaiste/tmux.vim'

# vim
[[plugins]]
repo = 'ynkdir/vim-vimlparser'

# deepcopy(g:quickrun#default_config)でvimconsole#widthのエラーが出るのでコメントアウト
# [[plugins]]
# repo = 'rbtnn/vimconsole.vim'

[[plugins]]
repo = 'thinca/vim-ft-help_fold'
