# unite {{{1
# ============================================================================
[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'basyura/unite-mdfind'
on_source = 'unite.vim'
# }}}

[[plugins]]
repo = 'Shougo/vimfiler.vim'
on_source = 'unite.vim'
on_map = '<Plug>'

# vimshell {{{1
# ============================================================================
[[plugins]]
repo = 'Shougo/vimshell.vim'
depends = ['vim-vcs', 'unite.vim']
on_cmd = ['VimShell', 'VimShellBufferDir', 'VimShellInteractive', 'VimShellPop']

[[plugins]]
repo = 'Shougo/vim-vcs'
# }}}

[[plugins]]
repo = 'oplatek/Conque-Shell'
on_cmd = ['ConqueTerm', 'ConqueTermSplit', 'ConqueTermTab', 'ConqueTermVSplit']

# neocomplete {{{1
# ============================================================================
[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = [
    'neoinclude.vim',
    'neosnippet.vim', 'vim-snippets'
]
on_i = 1
# vim_version = '7.3.825'

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'
# vim_version = '7.3.825'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'honza/vim-snippets'

# operator {{{1
# ============================================================================
[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
on_map = '<plug>(operator-surround-'

[[plugins]]
repo = 'tyru/operator-camelize.vim'
depends = 'vim-operator-user'
on_map = '<Plug>(operator-camelize-'

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
on_map = '<Plug>(operator-replace)'

[[plugins]]
repo = 'osyo-manga/vim-operator-search'
depends = 'vim-operator-user'
on_map = '<Plug>(operator-search)'

# textobj {{{1
# ============================================================================
[[plugins]]
repo = 'kana/vim-textobj-entire'
on_map = '<Plug>(textobj-entire'

[[plugins]]
repo = 'osyo-manga/vim-textobj-context'
on_map = '<Plug>(textobj-context-'

[[plugins]]
repo = 'kana/vim-textobj-lastpat'
on_map = '<Plug>(textobj-lastpat-'

[[plugins]]
repo = 'glts/vim-textobj-comment'
on_map = '<Plug>(textobj-comment-'
# }}}

[[plugins]]
repo = 'kana/vim-smartword'
on_map = '<Plug>'

# tmsanrinsha/vim-fakeclip {{{
[[plugins]]
repo = 'tmsanrinsha/vim-fakeclip'
if = "$SSH_CLIENT != ''"
on_map = '<Plug>'
hook_add = '''
    xmap  "&D           <Plug>(fakeclip-screen-D)
    nmap  "&D           <Plug>(fakeclip-screen-D)
    nmap  "&dd          <Plug>(fakeclip-screen-dd)
    xmap  "&d           <Plug>(fakeclip-screen-d)
    nmap  "&d           <Plug>(fakeclip-screen-d)
    xmap  "&[P          <Plug>(fakeclip-screen-[P)
    xmap  "&[p          <Plug>(fakeclip-screen-[p)
    xmap  "&]P          <Plug>(fakeclip-screen-]P)
    xmap  "&]p          <Plug>(fakeclip-screen-]p)
    xmap  "&gP          <Plug>(fakeclip-screen-gP)
    xmap  "&gp          <Plug>(fakeclip-screen-gp)
    xmap  "&P           <Plug>(fakeclip-screen-P)
    xmap  "&p           <Plug>(fakeclip-screen-p)
    nmap  "&[P          <Plug>(fakeclip-screen-[P)
    nmap  "&[p          <Plug>(fakeclip-screen-[p)
    nmap  "&]P          <Plug>(fakeclip-screen-]P)
    nmap  "&]p          <Plug>(fakeclip-screen-]p)
    nmap  "&gP          <Plug>(fakeclip-screen-gP)
    nmap  "&gp          <Plug>(fakeclip-screen-gp)
    nmap  "&P           <Plug>(fakeclip-screen-P)
    nmap  "&p           <Plug>(fakeclip-screen-p)
    xmap  "&Y           <Plug>(fakeclip-screen-Y)
    xmap  "&y           <Plug>(fakeclip-screen-y)
    nmap  "&yy          <Plug>(fakeclip-screen-Y)
    nmap  "&Y           <Plug>(fakeclip-screen-Y)
    nmap  "&y           <Plug>(fakeclip-screen-y)
    xmap  "*D           <Plug>(fakeclip-D)
    nmap  "*D           <Plug>(fakeclip-D)
    nmap  "*dd          <Plug>(fakeclip-dd)
    xmap  "*d           <Plug>(fakeclip-d)
    nmap  "*d           <Plug>(fakeclip-d)
    xmap  "*[P          <Plug>(fakeclip-[P)
    xmap  "*[p          <Plug>(fakeclip-[p)
    xmap  "*]P          <Plug>(fakeclip-]P)
    xmap  "*]p          <Plug>(fakeclip-]p)
    xmap  "*gP          <Plug>(fakeclip-gP)
    xmap  "*gp          <Plug>(fakeclip-gp)
    xmap  "*P           <Plug>(fakeclip-P)
    xmap  "*p           <Plug>(fakeclip-p)
    nmap  "*[P          <Plug>(fakeclip-[P)
    nmap  "*[p          <Plug>(fakeclip-[p)
    nmap  "*]P          <Plug>(fakeclip-]P)
    nmap  "*]p          <Plug>(fakeclip-]p)
    nmap  "*gP          <Plug>(fakeclip-gP)
    nmap  "*gp          <Plug>(fakeclip-gp)
    nmap  "*P           <Plug>(fakeclip-P)
    nmap  "*p           <Plug>(fakeclip-p)
    xmap  "*Y           <Plug>(fakeclip-Y)
    xmap  "*y           <Plug>(fakeclip-y)
    nmap  "*yy          <Plug>(fakeclip-Y)
    nmap  "*Y           <Plug>(fakeclip-Y)
    nmap  "*y           <Plug>(fakeclip-y)
    xmap  "+D           <Plug>(fakeclip-D)
    nmap  "+D           <Plug>(fakeclip-D)
    nmap  "+dd          <Plug>(fakeclip-dd)
    xmap  "+d           <Plug>(fakeclip-d)
    nmap  "+d           <Plug>(fakeclip-d)
    xmap  "+[P          <Plug>(fakeclip-[P)
    xmap  "+[p          <Plug>(fakeclip-[p)
    xmap  "+]P          <Plug>(fakeclip-]P)
    xmap  "+]p          <Plug>(fakeclip-]p)
    xmap  "+gP          <Plug>(fakeclip-gP)
    xmap  "+gp          <Plug>(fakeclip-gp)
    xmap  "+P           <Plug>(fakeclip-P)
    xmap  "+p           <Plug>(fakeclip-p)
    nmap  "+[P          <Plug>(fakeclip-[P)
    nmap  "+[p          <Plug>(fakeclip-[p)
    nmap  "+]P          <Plug>(fakeclip-]P)
    nmap  "+]p          <Plug>(fakeclip-]p)
    nmap  "+gP          <Plug>(fakeclip-gP)
    nmap  "+gp          <Plug>(fakeclip-gp)
    nmap  "+P           <Plug>(fakeclip-P)
    nmap  "+p           <Plug>(fakeclip-p)
    xmap  "+Y           <Plug>(fakeclip-Y)
    xmap  "+y           <Plug>(fakeclip-y)
    nmap  "+yy          <Plug>(fakeclip-Y)
    nmap  "+Y           <Plug>(fakeclip-Y)
    nmap  "+y           <Plug>(fakeclip-y)
    imap  <C-R><C-P>&   <Plug>(fakeclip-screen-insert-p)
    map!  <C-R><C-O>&   <Plug>(fakeclip-screen-insert-o)
    map!  <C-R><C-R>&   <Plug>(fakeclip-screen-insert-r)
    map!  <C-R>&        <Plug>(fakeclip-screen-insert)
    imap  <C-R><C-P>*   <Plug>(fakeclip-insert-p)
    map!  <C-R><C-O>*   <Plug>(fakeclip-insert-o)
    map!  <C-R><C-R>*   <Plug>(fakeclip-insert-r)
    map!  <C-R>*        <Plug>(fakeclip-insert)
    imap  <C-R><C-P>+   <Plug>(fakeclip-insert-p)
    map!  <C-R><C-O>+   <Plug>(fakeclip-insert-o)
    map!  <C-R><C-R>+   <Plug>(fakeclip-insert-r)
    map!  <C-R>+        <Plug>(fakeclip-insert)
'''
# }}}

[[plugins]]
repo = 'tmsanrinsha/DirDiff.vim'
on_cmd = 'DirDiff'

[[plugins]]
repo = 'osyo-manga/vim-marching'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'quark-zju/vim-cpp-auto-include'
external_commands = 'ruby'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'php']

[[plugins]]
repo = 'maksimr/vim-jsbeautify'
external_commands = 'node'
on_ft = ['javascript', 'css', 'html']

[[plugins]]
repo = 'stephpy/vim-php-cs-fixer'
on_ft = ['PhpCsFixerFixDirectory', 'PhpCsFixerFixFile']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
depends = ['jedi-vim']
on_ft = ['python', 'python3']

[[plugins]]
repo = 'tmsanrinsha/previm'
on_cmd = ['PrevimOpen']
on_ft = ['markdown']

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_cmd = ['TableModeToggle', 'Tableize', 'TableAddFormula', 'TableEvalFormulaLine']

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'
on_cmd = ['AnsiEsc']

[[plugins]]
repo = 'LeafCage/yankround.vim'
on_map = '<Plug>'
on_sources = 'unite.vim'
# vim_version = '7.3'

[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = 'GundoToggle'

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'Lokaltog/vim-easymotion'
on_map = '<Plug>(easymotion-'

[[plugins]]
repo = 'thinca/vim-ref'
on_cmd = ['Ref', 'Man']

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
depends = ['vim-quickrun', 'shabadou.vim', 'vim-hier', 'quickfixstatus', 'vim-qfsigns']

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'KazuakiM/vim-qfsigns'

[[plugins]]
repo = 'joonty/vdebug'
on_ft = ['php']

[[plugins]]
repo = 'thinca/vim-partedit'
on_cmd = 'Partedit'

[[plugins]]
repo = 'simeji/winresizer'
on_cmd = 'WWinResizerStartResize'
hook_add = '''
  let g:winresizer_start_key = '<A-w>'
'''

[[plugins]]
repo = 't9md/vim-quickhl'
on_map = '<Plug>(quickhl-'

[[plugins]]
repo = 'DrawIt'
on_map = ';di'
on_cmd = 'DrawIt'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_func = ['openbrowser#search', 'OpenBrowser']
on_map = '<Plug>(openbrowser-'

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_source = 'unite.vim'

[[plugins]]
repo = 'glidenote/memolist.vim'
on_cmd = ['MemoNew', 'MemoList', 'MemoGrep']

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = 'unite.vim'
on_cmd = ['Junkfile', 'JunkfileOpen', 'JunkfileFiletype']

[[plugins]]
repo = 'mattn/qiita-vim'
on_source = 'unite.vim'
on_cmd = ['Qiita']

[[plugins]]
repo = 'mattn/gist-vim'
depends = 'webapi-vim'
on_cmd = ['Gist']

[[plugins]]
repo = 'neilagabriel/vim-geeknote'
on_cmd = ['Geeknote']

[[plugins]]
repo = 'haya14busa/vim-asterisk'
on_map = '<Plug>(asterisk-'

[[plugins]]
repo = 'kannokanno/vim-helpnew'
on_cmd = 'HelpNew'

[[plugins]]
repo = 'rbtnn/vimconsole.vim'
on_cmd = 'VimConsoleToggle'

[[plugins]]
repo = 'tomtom/tcomment_vim'
on_map = ['<Plug>TComment_', 'gc']

[[plugins]]
repo = 'gregsexton/gitv'
on_cmd = ['Gitv']
